name = "FastBenchmark"
uuid = "5aff02d6-5711-4357-aa22-8dd251b5ff14"
authors = ["alfaromartino <alfaromartino@gmail.com>"]
version = "0.1.0"

[deps]
Chairmarks = "0ca39b1e-fe0b-4e98-acfc-b1656634c4de"
